In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import cv2
import numpy as np

In [3]:
pwd

'C:\\Users\\Alok'

# Load / Read image

In [4]:
# Load an immage
img=cv2.imread('Modi.jpg',1)

Let's take a closer look at how image are stored

In [5]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [6]:
#shape gives dimension of the image
img.shape

(1358, 1500, 3)

In [7]:
#Displa image
cv2.imshow('PM',img)
#'waitkey'
cv2.waitKey(200)

cv2.destroyAllWindows()

In [8]:
img=cv2.imread('Modi.jpg')
cv2.imshow('PM', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
#save image
cv2.imwrite('pm_b_w.jpg',img)

True

In [10]:
#Resize Image
img=cv2.imread('Modi.jpg')

resized_image=cv2.resize(img,(500,500))
gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)
cv2.imshow('Modi Imag',gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
img.shape[0]*0.5

679.0

In [12]:
img.shape[1]*0.5

750.0

# Face Detection using HAAR Cascade Classifiers

In [13]:
face_classifier=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
#Load our image then convert it to grayscale
image=cv2.imread("Modi.jpg")
image=cv2.resize(img,(500,500))
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
#Tunning casecade classifiers
faces=face_classifier.detectMultiScale(gray,1.05,5)

In [14]:
print(faces)

[[205  79 217 217]]


In [15]:
face_classifier=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

#Load our image then convert it to grayscale
image=cv2.imread("Modi.jpg")
image=cv2.resize(image,(500,500))
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

#Tunning casecade classifiers
faces=face_classifier.detectMultiScale(gray,1.05,5)

if faces is ():
    print('No faces found')
for(x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,100),1)
cv2.imshow('Face Detection',image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Alok\AppData\Local\Temp\ipykernel_9212\3730808640.py:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


# Face & Eye Detection using HAAR Cascade Classifiers in Image

In [16]:
face_classifier=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_classifier=cv2.CascadeClassifier('haarcascade_eye.xml')

img=cv2.imread('modi.jpg')
resized_image=cv2.resize(img,(500,500))
gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray,1.3,5)

#when no faces detected,face calssifier return and empty tuple
if faces is ():
    print('No Face Found')
for (x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray=gray[y:y+h,x:x+w]
    roi_color=resized_image[y:y+h,x:x+w]
    eyes=eye_classifier.detectMultiScale(roi_gray)
    for(ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
cv2.imshow('img',resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Alok\AppData\Local\Temp\ipykernel_9212\1688810624.py:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


# Capture a video

In [17]:
#  doing some Face recognition with the webcam
import cv2
video=cv2.VideoCapture(0) #0--webcam
while True:
    check,frame=video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video',gray)
    if cv2.waitKey(1)==ord('q'):
        break
video.release()
cv2.destroyAllWindows()

# Face & Eye Detection using HAAR Cascade Classifiers

In [18]:
#
face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade=cv2.CascadeClassifier('haarcascade_eye.xml')

def detect(gray,frame):
    faces=face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
         cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
         roi_gray=gray[y:y+h,x:x+w]
         roi_color=resized_image[y:y+h,x:x+w]
         eyes=eye_classifier.detectMultiScale(roi_gray)
         for(ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    return frame

#Doing some face recognition with the webcam
video=cv2.VideoCapture(0)

while True:
     check,frame=video.read()
     gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
     canvas=detect(gray,frame)
     cv2.imshow('video',canvas)
     if cv2.waitKey(1)==ord('q'):
         break
   
video.release()
cv2.destroyAllWindows()
    

# Pedistrain Detection

In [19]:
import cv2
#body
body_classifier=cv2.CascadeClassifier('haarcascade_fullbody.xml')
cap=cv2.VideoCapture("walking.avi")
#Loop
while cap.isOpened():
    
    #read first frame
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    #pass from to our body classifier
    bodies=body_classifier.detectMultiScale(gray,1.2,3)
    
    #Extract bounding boxes for any bodies identified
    for(x,y,w,h) in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        cv2.imshow('Pedestrains',frame)
    if cv2.waitKey(1)==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [20]:
import time
# Create our body classifier
car_classifier=cv2.CascadeClassifier('haarcascade_car.xml')

# Initiate video capture for video file
cap=cv2.VideoCapture('cars.avi')

# loop once video is successfully loadded
while cap.isOpened():
    time.sleep(.05)
    # Read first frame
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    # pass frame to our car cassifier 
    cars=car_classifier.detectMultiScale(gray,1.4,2)
    
    #Extract bounding boxes for any bodies identified
    for(x,y,w,h) in cars:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255),2)
        cv2.imshow('Cars',frame)
    if cv2.waitKey(1)==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()