# Introduction
* Numpy is a open source Python Library that aid in mathematical and scientific programming.
* It is used for working with arrays,Linear algebra,Fourier transform & nd metrics.
* In Python list  of array are very slow, but in numpy arrray object 50 times faster than list.
* It perform mathematical and statistical operation due to it's fast & memory efficient.It is optimized to work with least cpu architecture.
* When axis=0 ------>column , axis=1------>row

In [1]:
import numpy as np
np.__version__ # check virsion of numpy

'1.21.5'

# **ndarray:-** numpy.array(object)
* It is created using an array function in numpy.

In [2]:
a=[1,2,3,4,5]
b=np.array(a)
print(b)
b

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [3]:
print(type(b))

<class 'numpy.ndarray'>


# Creating Numpy Arrays from a list
**1. Zero Dimensional Array**

In [4]:
arr=np.array(42)
print(arr)
type(arr)

42


numpy.ndarray

To check No. of dimension of array

In [5]:
print('No. of dimension is', arr.ndim)

No. of dimension is 0


**2.One Dimensional Array**

In [6]:
a=np.array([0,1,2,3])
print(a)
type(a)

[0 1 2 3]


numpy.ndarray

In [7]:
a.shape

(4,)

In [8]:
a.ndim #To check No. of dimension of array

1

**3.Two Dimensional Array**

In [9]:
c=[0,1,2],[3,4,5]
c=np.array([[0,1,2],[3,4,5]])
print(c)
type(c)

[[0 1 2]
 [3 4 5]]


numpy.ndarray

In [10]:
c.shape

(2, 3)

In [11]:
c.ndim #To check No. of dimension of array

2

In [12]:
# Matrix
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(my_matrix)
print(matrix)
type(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [13]:
matrix.shape

(3, 3)

In [14]:
matrix.ndim

2

In [150]:
a=np.array([[10,20],[30,40]])
print(a)
a[1,1]

[[10 20]
 [30 40]]


40

In [152]:
# assigning value
a[1,1]=25
a

array([[10, 20],
       [30, 25]])

# Function for creating array:-

**arange:-**

* Syntax : np.arange (start,end,step)
* It is an array-valued version of the built-in python range function

In [21]:
arr=np.arange(10,101,10)
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


**linspace**
* Syntax : np.linspace (start,end,num_of_samples)
* Return evenly spaced numbers over a specified interval

In [35]:
l=np.linspace (0,10,11)
l

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**zeros:-**
* Syntax : np.zeros(shape)
* Generate arrays of zeros

In [40]:
np.zeros(1)

array([0.])

In [45]:
np.zeros(5,)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

**ones:-**
* Syntax : np.ones(shape)
* Generate arrays of zeros

In [54]:
np.ones((5),dtype=int)

array([1, 1, 1, 1, 1])

**random.randint :-**
* Syntax : np.random.randint (start,end,num_of_samples)
* Return random integers from start(incusive) to end(exclusive)

In [55]:
np.random.randint(1,20,5) # randomly choose 5 num from 1 to 20

array([ 3,  1,  5,  6, 12])

**Flattening :** Converting nd array to 1D array

In [153]:
a=np.array([[0,1,2],[3,4,5]])
a.ravel()

array([0, 1, 2, 3, 4, 5])

**Reshape :**Any shape can be converted

In [157]:
arr=np.arange(20)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


In [165]:
a1=arr.reshape(5,4) # 5*4=20
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

**Transpose array :** convert row into column

In [169]:
c=a1.T
print(c)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


# **Accessing elements**
* 1.Accessing a single value through Indexing
* 2.Accessing a multiple values based on slicing
* 3.Accessing a multiple values based on Indexing
* 4.Accessing a multiple values based on condition

**1.Accessing a single value through Indexing**

In [57]:
a=np.arange(10,101,10)
print(a)
a[2]

[ 10  20  30  40  50  60  70  80  90 100]


30

**2.Accessing a multiple values based on slicing**

In [66]:
a[1:100:2]

array([ 20,  40,  60,  80, 100])

**3.Accessing a multiple values based on Indexing**

In [67]:
a[[0,1,2,3]]

array([10, 20, 30, 40])

**4.Accessing a multiple values based on condition (mask indexing or fancy indexing)**

In [68]:
a%3==0

array([False, False,  True, False, False,  True, False, False,  True,
       False])

In [70]:
a[a%2==0]

array([ 10,  20,  30,  40,  50,  50,  70,  80,  90, 100])

# Numpy is mutable
* 1.Replace
* 2.Add
* 3.Remove

**1.Replace**
* Replacing a single value in a array

In [71]:
a[5]=50
print(a)

[ 10  20  30  40  50  50  70  80  90 100]


* Replacing a multiple values in a array

In [73]:
a[[1,5]]=80
a

array([ 10,  80,  30,  40,  50,  80,  70,  80,  90, 100])

**2.Add**

In [76]:
b=np.append(a,[110,120])
b

array([ 10,  80,  30,  40,  50,  80,  70,  80,  90, 100, 110, 120])

**3.Remove**
* Delete a single in value in a array

In [82]:
print('Given Numpy:',a)
b=np.delete(a,8)
b

Given Numpy: [ 10  80  30  40  50  80  70  80  90 100]


array([ 10,  80,  30,  40,  50,  80,  70,  80, 100])

* Delete a multiple in values in a array

In [83]:
b=np.delete(a,[1,2])
b

array([ 10,  40,  50,  80,  70,  80,  90, 100])

**Sort**

In [85]:
np.sort([4,6,3,2,1])

array([1, 2, 3, 4, 6])

**Copy array**

In [89]:
a=np.array([1,2,3])
print('given :',a)
b=a.copy()
b[0]=100
print(b)

given : [1 2 3]
[100   2   3]


**around()**

In [93]:
arr=np.array([1.432,3.05,5.9])
np.around(arr)

array([1., 3., 6.])

In [95]:
np.around(arr,2)

array([1.43, 3.05, 5.9 ])

# Operations
**Arithmetic Operations**

In [97]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [98]:
a+1

array([2, 3, 4, 5])

In [99]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [101]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8,])
c=np.array([1,2,3,4])          
print(a,b,c)

[1 2 3 4] [5 6 7 8] [1 2 3 4]


In [104]:
a+b

array([ 6,  8, 10, 12])

In [105]:
a-b

array([-4, -4, -4, -4])

In [106]:
a*b

array([ 5, 12, 21, 32])

**Comparision operations**

In [110]:
a==c

array([ True,  True,  True,  True])

In [109]:
a>b

array([False, False, False, False])

In [111]:
np.array_equal(a,b)

False

In [112]:
np.array_equal(a,c)

True

**Trignometric operation**

In [134]:
a=np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [135]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [136]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219])

In [137]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501])

In [139]:
np.log(a)

C:\Users\Alok\AppData\Local\Temp\ipykernel_12176\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

In [140]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

**Statistical operation**

In [142]:
np.mean(a)

2.5

In [143]:
np.median(a)

2.5

In [146]:
np.std(a)

1.707825127659933

In [147]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [148]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])